"""tables

Revision ID: 60a6b4a2da51
Revises: 
Create Date: 2020-09-28 04:30:48.403760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60a6b4a2da51'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AllPosts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Numeric(precision=30, scale=0), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('media_type', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('permalink', sa.String(length=100), nullable=True),
    sa.Column('count_comments', sa.Integer(), nullable=True),
    sa.Column('count_like', sa.Integer(), nullable=True),
    sa.Column('count_engagement', sa.Integer(), nullable=True),
    sa.Column('count_impressions', sa.Integer(), nullable=True),
    sa.Column('count_reach', sa.Integer(), nullable=True),
    sa.Column('count_saved', sa.Integer(), nullable=True),
    sa.Column('count_video_views', sa.Integer(), nullable=True),
    sa.Column('media_url', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_AllPosts_post_id'), 'AllPosts', ['post_id'], unique=True)
    op.create_index(op.f('ix_AllPosts_timestamp'), 'AllPosts', ['timestamp'], unique=False)
    op.create_table('AllStories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Numeric(precision=30, scale=0), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('count_impressions', sa.Integer(), nullable=True),
    sa.Column('count_reach', sa.Integer(), nullable=True),
    sa.Column('count_tapsforward', sa.Integer(), nullable=True),
    sa.Column('count_tapsback', sa.Integer(), nullable=True),
    sa.Column('count_exits', sa.Integer(), nullable=True),
    sa.Column('count_replies', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_AllStories_story_id'), 'AllStories', ['story_id'], unique=False)
    op.create_index(op.f('ix_AllStories_timestamp'), 'AllStories', ['timestamp'], unique=False)
    op.create_table('AutomatedDailyFetch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('numFollowing', sa.Integer(), nullable=True),
    sa.Column('numFollowers', sa.Integer(), nullable=True),
    sa.Column('numPosts', sa.Integer(), nullable=True),
    sa.Column('numDailyVisits', sa.Integer(), nullable=True),
    sa.Column('numDailyFollowers', sa.Integer(), nullable=True),
    sa.Column('numDailyReach', sa.Integer(), nullable=True),
    sa.Column('numDailyImpressions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_AutomatedDailyFetch_date'), 'AutomatedDailyFetch', ['date'], unique=False)
    op.create_index(op.f('ix_AutomatedDailyFetch_time'), 'AutomatedDailyFetch', ['time'], unique=False)
    op.create_table('DailyAccountInfoFetch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('numFollowing', sa.Integer(), nullable=True),
    sa.Column('numFollowers', sa.Integer(), nullable=True),
    sa.Column('numPosts', sa.Integer(), nullable=True),
    sa.Column('numDailyVisits', sa.Integer(), nullable=True),
    sa.Column('numDailyFollowers', sa.Integer(), nullable=True),
    sa.Column('numDailyReach', sa.Integer(), nullable=True),
    sa.Column('numDailyImpressions', sa.Integer(), nullable=True),
    sa.Column('profilePictureUrl', sa.Text(), nullable=True),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_DailyAccountInfoFetch_date'), 'DailyAccountInfoFetch', ['date'], unique=False)
    op.create_index(op.f('ix_DailyAccountInfoFetch_time'), 'DailyAccountInfoFetch', ['time'], unique=False)
    op.create_table('Webhooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('hook_type', sa.String(length=20), nullable=True),
    sa.Column('comment_id', sa.Numeric(precision=30, scale=0), nullable=True),
    sa.Column('comment_text', sa.Text(), nullable=True),
    sa.Column('media_id', sa.Numeric(precision=30, scale=0), nullable=True),
    sa.Column('story_id', sa.Numeric(precision=30, scale=0), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Webhooks_timestamp'), 'Webhooks', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Webhooks_timestamp'), table_name='Webhooks')
    op.drop_table('Webhooks')
    op.drop_index(op.f('ix_DailyAccountInfoFetch_time'), table_name='DailyAccountInfoFetch')
    op.drop_index(op.f('ix_DailyAccountInfoFetch_date'), table_name='DailyAccountInfoFetch')
    op.drop_table('DailyAccountInfoFetch')
    op.drop_index(op.f('ix_AutomatedDailyFetch_time'), table_name='AutomatedDailyFetch')
    op.drop_index(op.f('ix_AutomatedDailyFetch_date'), table_name='AutomatedDailyFetch')
    op.drop_table('AutomatedDailyFetch')
    op.drop_index(op.f('ix_AllStories_timestamp'), table_name='AllStories')
    op.drop_index(op.f('ix_AllStories_story_id'), table_name='AllStories')
    op.drop_table('AllStories')
    op.drop_index(op.f('ix_AllPosts_timestamp'), table_name='AllPosts')
    op.drop_index(op.f('ix_AllPosts_post_id'), table_name='AllPosts')
    op.drop_table('AllPosts')
    # ### end Alembic commands ###
