"""tables update fix

Revision ID: a953bd9d9e4c
Revises: f8b90e0e0c06
Create Date: 2020-09-28 08:52:36.636341

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a953bd9d9e4c'
down_revision = 'f8b90e0e0c06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FetchLog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('fetch_type', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_FetchLog_timestamp'), 'FetchLog', ['timestamp'], unique=False)
    op.drop_index('ix_LatestFetch_timestamp', table_name='LatestFetch')
    op.drop_table('LatestFetch')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LatestFetch',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"LatestFetch_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('fetch_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='LatestFetch_pkey')
    )
    op.create_index('ix_LatestFetch_timestamp', 'LatestFetch', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_FetchLog_timestamp'), table_name='FetchLog')
    op.drop_table('FetchLog')
    # ### end Alembic commands ###
