"""tables update

Revision ID: f8b90e0e0c06
Revises: 34febc91f8d3
Create Date: 2020-09-28 08:50:24.932635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8b90e0e0c06'
down_revision = '34febc91f8d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LatestFetch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('fetch_type', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_LatestFetch_timestamp'), 'LatestFetch', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_LatestFetch_timestamp'), table_name='LatestFetch')
    op.drop_table('LatestFetch')
    # ### end Alembic commands ###
